[build]
  publish = "."
  command = "node scripts/build-env.js"

[build.environment]
# Allow Firebase public config to be emitted for the browser
  SECRETS_SCAN_OMIT_PATHS = "js/env.js"
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID,VITE_FIREBASE_MEASUREMENT_ID"
  # If preferred, disable entirely:
  # SECRETS_SCAN_ENABLED = "false"
